name: pearl

networks:
  pearl:
    driver: bridge

services:
  database:
    image: postgres:16.3
    networks:
      - pearl
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: pearljam
      POSTGRES_PASSWORD: pearljam
    volumes:
      - ./dbvol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pearljam"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 3s

  # Admin UI for the database
  adminer:
    image: adminer
    networks:
      - pearl
    restart: always
    ports:
      - 8080:8080

  # RabbitMQ
  rabbit-mq:
    image: rabbitmq:3.13.2-management
    restart: always
    networks:
      - pearl
    volumes:
      - ./rabbitmq:/var/hostfiles
    environment:
      - RABBITMQ_ENABLED_PLUGINS_FILE=/var/hostfiles/plugins_config
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692

  # Prometheus
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - pearl
    ports:
      - 9090:9090

  # Grafana
  grafana:
    image: grafana/grafana
    restart: always
    networks:
      - pearl
    ports:
      - 3000:3000

volumes:
  dbvol:
  rabbitmq:
  prometheus:
